/*
** Copyright © Bart Kampers
*/

package randd.motormanagement.swing;

import java.awt.*;
import randd.motormanagement.communication.RemoteSystem;
import randd.motormanagement.system.*;


public class TimerPanel extends javax.swing.JPanel {


    public TimerPanel(Monitor monitor, String title) {
        this.monitor = monitor;
        this.title = title;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prescalerLabel = new javax.swing.JLabel();
        prescalerFormattedTextField = new javax.swing.JFormattedTextField();
        periodLabel = new javax.swing.JLabel();
        periodFormattedTextField = new javax.swing.JFormattedTextField();
        counterLabel = new javax.swing.JLabel();
        counterFormattedTextField = new javax.swing.JFormattedTextField();
        sendButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(title));

        prescalerLabel.setText("Prescaler");

        periodLabel.setText("Period");

        counterLabel.setText("Counter");

        counterFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prescalerLabel)
                            .addComponent(periodLabel)
                            .addComponent(counterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(periodFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(counterFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prescalerFormattedTextField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sendButton)))
                .addContainerGap())
            .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prescalerFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prescalerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodLabel)
                    .addComponent(periodFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(counterLabel)
                    .addComponent(counterFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        if (monitor.getMessenger() != null) {
            try {
                String result = monitor.getMessenger().modifyIgnitionTimerSettings(settings());
                if (RemoteSystem.OK.equals(result)) {
                    messageLabel.setForeground(new Color(23, 219, 36));
                }
                else {
                    messageLabel.setForeground(Color.RED);                
                }
                messageLabel.setText(result);
            }
            catch (InterruptedException | org.json.JSONException ex) {
                messageLabel.setForeground(Color.RED);
                messageLabel.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    
    private TimerSettings settings() {
        TimerSettings timerSettings = new TimerSettings();
        timerSettings.setPrescaler(Integer.parseInt(prescalerFormattedTextField.getText()));
        timerSettings.setPeriod(Integer.parseInt(periodFormattedTextField.getText()));
        timerSettings.setCounter(Integer.parseInt(counterFormattedTextField.getText()));
        return timerSettings;
    }
    
    
    private final Monitor monitor;
    private final String title;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField counterFormattedTextField;
    private javax.swing.JLabel counterLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JFormattedTextField periodFormattedTextField;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JFormattedTextField prescalerFormattedTextField;
    private javax.swing.JLabel prescalerLabel;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
    
}
